name: Build

on:
  push:
    branches: [ master ]
  pull_request:
  release:
    types: [ created ]

jobs:
  build-phar:
    runs-on: ubuntu-latest
    name: Build PHAR
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.1' ]
    steps:
      -   name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 0

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}
            ini-values: phar.readonly=0
            tools: composer
            coverage: none

      -   name: Install Composer dependencies
          uses: ramsey/composer-install@v2

      -   name: Build PHAR
          run: |
            cp application application.phar
            composer build -- --build-version

      # Smoke test
      -   name: Ensure the PHAR works
          run: builds/branch-usage-checker --version

      -   uses: actions/upload-artifact@v3
          name: Upload the PHAR artifact
          with:
            name: branch-usage-checker
            path: builds/branch-usage-checker

  publish-phar:
    runs-on: ubuntu-latest
    name: Publish the PHAR
    needs:
      - 'build-phar'
    if: github.event_name == 'release'
    steps:
      -   uses: actions/download-artifact@v3
          with:
            name: branch-usage-checker
            path: builds/

      -   name: Upload box.phar
          uses: softprops/action-gh-release@v1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            files: builds/branch-usage-checker
